### ISSUE TITLE
Verblijfplaatshistorie v2.0

### ISSUE THREAD

**Issue by CathyDingemanse** [BRP-API/Haal-Centraal-BRP-historie-bevragen#112]
Productiedatum: 2 september 2024
- [ ] Waarom belangrijk: userstory [https://github.com/BRP-API/Haal-Centraal-BRP-historie-bevragen/issues/111](url)
- [x] [A&P](https://github.com/BRP-API/brp-shared-dotnet/pull/52)
- [ ] Dataservice
- [ ] Informatieservice
- [ ] Documentatie
- [ ] Acceptatietesten ACC
- [ ] Acceptatietesten LAP en vrijgave advies
- [ ] Productie acceptatietest
