### ISSUE TITLE
partner historie

### ISSUE THREAD

**Issue by MelvLee** [BRP-API/Haal-Centraal-BRP-historie-bevragen#119]
Release naar productie: 01-12-2024?

- [x] code historie data service in haal centraal repo overzetten naar historie-data-service repo
- [ ] oas spec voor historie-informatie-service
- [ ] oas spec voor historie-data-service
- [ ] autorisatie
- [ ] features data-service
- [ ] features informatie-service
- [ ] features autorisatie
- [ ] test op ACC
- [ ] vrijgaveadvies
- [ ] deployen naar proefomgeving
- [ ] deployen naar productie

**Comment by Patrick-4488** [comment]
overgebleven taken bij: https://github.com/orgs/BRP-API/projects/2/views/1?pane=issue&itemId=81898983
